# Generated by Django 5.2 on 2025-05-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqft', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('lot_size', models.FloatField()),
                ('year_built', models.IntegerField()),
                ('stories', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=50)),
                ('garage', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('predicted_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
